### ISSUE TITLE
Cannot find module nodejavabridge_bindings.node (desperate user here)

### ISSUE THREAD

**Issue by OlivierAlves** [nodenica/jt400.js#16]
Hi !
I am on this problem for several days and trust me I tried EVERTHING I can think of and absolutely NOTHING works... I really need help on this. Please,

So I have a simple file test,js that looks like this:
```
var Database = require('jt400');
var database = new Database();

var config = {
  libpath: './jt400.jar',
  drivername: 'com.ibm.as400.access.AS400JDBCDriver',
  url: 'jdbc:as400: *hidden but it works as this url is used in other programs*'
};

database.initialize(config);

// SELECT statements must be run with execute()
database.execute('SELECT * FROM TABLE1');

database.on('execute', function(error, results) {
  if (error) {
    console.log(error);
  }
  else {
    console.log(results);
  }
});
```
Whenever I do node test.js here is the result:

Cannot find module 
module.js:328
    throw err;
    ^

Error: Cannot find module '*path*/resttest/node_modules/jt400/node_modules/java/build/Release/nodejavabridge_bindings.node'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (*path*/resttest/node_modules/jt400/node_modules/java/lib/nodeJavaBridge.js:21:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

Can someone please help me ?
Thank you
(P.S.: yes I have java set in my env path)

**Comment by OlivierAlves** [comment]
P.P.S: yes i have seen that issue https://github.com/nodenica/jt400.js/issues/1 ....... doesn't work for me
